fix: vectorStore 중복 저장 수정 및 InitializingBean 생성
publiko2024/kobot_backend pull request #5
Opened 2024-08-17 23:24 UTC by SeokCheol-Lee

## #️⃣연관된 이슈

> #4 

## 📝작업 내용

> vectorStore 데이터 중복 저장 수정
> vectorStore에 데이터 저장시 토큰화 과정에서 발생하는 문자 인코딩 문제 해결
> InitializingBean 생성으로 중복적으로 index check 로직 수정

2024-08-18 11:35 UTC, yuna1212 requested changes

2024-08-18 11:35 UTC, yuna1212 commented on src/main/java/com/kobot/backend/common/InitializingBean.java
> +            log.error("Error checking or creating index: {}", e.getMessage(), e);
`e.getMessage()`는 없어도 돼요. `Throwalbe` 객체를 넘기면 stack trace, 에러 메시지를 같이 출력해요.
그래서 이 경우는
```java
log.error("Error checking or creating index.", e);
```
정도도 괜찮습니다.

2024-08-18 11:35 UTC, yuna1212 commented on src/main/java/com/kobot/backend/service/EmbeddingService.java
`sentenceTokens.size() > maxTokens`인 경우도 있을텐데, 여기에 _warn_으로 `sentence`가 뭔지 log 하나 남겨두는건 어떨까요? 우리 의도랑 다른 케이스가 발생한거니까 로그 하나 있음 문제 파악하기 좋을 것 같아서여

2024-08-18 13:16 UTC, JeongJunSeo99 reviewed
Bean 초기화 시 인덱스 체크하는걸로 로직 수정한 부분 인상깊게 봤습니다

2024-08-18 23:36 UTC, SeokCheol-Lee commented on src/main/java/com/kobot/backend/common/InitializingBean.java
> +            log.error("Error checking or creating index: {}", e.getMessage(), e);
해당 내용 수정했습니다.

2024-08-18 23:41 UTC, SeokCheol-Lee commented on src/main/java/com/kobot/backend/service/EmbeddingService.java
넵 해당 사항 수정했습니다.

2024-08-19 03:21 UTC, yuna1212 approved these changes

2024-08-19 03:22 UTC, merged